name: Deploy ParcelJS Project to GitHub Pages

on:
  push:
    branches:
      - main    # Trigger deployment on push to the 'main' branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'    # You can specify the Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build project using Parcel
      run: npm run build      # This assumes you have a build script in package.json

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist     # ParcelJS output folder is 'dist' by default
